apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openssh-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "openssh-server.name" . }}
    helm.sh/chart: {{ include "openssh-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  sshd_config: |-
    # User-supplied sshd configuration:
    # The strategy used for options in the default sshd_config shipped with
    # OpenSSH is to specify options with their default value where
    # possible, but leave them commented.  Uncommented options override the
    # default value.

    {{- if .Values.sshd.port }}
    Port {{ .Values.sshd.port }}
    {{- else }}
    #Port 22
    {{- end }}
    {{- if .Values.sshd.addressFamily }}
    AddressFamily {{ .Values.sshd.addressFamily }}
    {{- else }}
    #AddressFamily any
    {{- end }}
    {{- if .Values.sshd.ipv4.enabled }}
    {{- if .Values.sshd.ipv4.listenAddress }}
    ListenAddress {{ .Values.sshd.ipv4.listenAddress }}
    {{- else }}
    #ListenAddress 0.0.0.0
    {{- end }}
    {{- end }}
    {{- if .Values.sshd.ipv6.enabled }}
    {{- if .Values.sshd.ipv6.listenAddress }}
    ListenAddress {{ .Values.sshd.ipv6.listenAddress }}
    {{- else }}
    #ListenAddress ::
    {{- end }}
    {{- end }}

    {{- if .Values.sshd.kexAlgorithms }}
    KexAlgorithms {{ .Values.sshd.kexAlgorithms }}
    {{- else }}
    KexAlgorithms diffie-hellman-group-exchange-sha256
    {{- end }}
    {{- if .Values.sshd.ciphers }}
    Ciphers {{ .Values.sshd.ciphers }}
    {{- else }}
    Ciphers aes256-cbc,aes256-ctr
    {{- end }}
    {{- if .Values.sshd.messageAuthenticationCodes }}
    MACs {{ .Values.sshd.messageAuthenticationCodes }}
    {{- else }}
    MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-256
    {{- end }}

    {{- if .Values.sshd.hostKeys }}
    {{- range .Values.sshd.hostKeys }}
    Hostkey {{ . }}
    {{- end }}
    {{- else }}
    #HostKey /etc/ssh/ssh_host_rsa_key
    #HostKey /etc/ssh/ssh_host_ecdsa_key
    #HostKey /etc/ssh/ssh_host_ed25519_key
    {{- end }}

    # Ciphers and keying
    {{- if .Values.sshd.reKeyLimit }}
    ReKeyLimit {{ .Values.sshd.reKeyLimit }}
    {{- else }}
    #RekeyLimit default none
    {{- end }}

    # Logging
    {{- if .Values.sshd.sysLogFacility }}
    SysLogFacility {{ .Values.sshd.sysLogFacility }}
    {{- else }}
    SyslogFacility AUTHPRIV
    {{- end }}
    {{- if .Values.sshd.logLevel }}
    LogLevel {{ .Values.sshd.logLevel }}
    {{- else }}
    LogLevel INFO
    {{- end }}

    # Authentication:

    {{- if .Values.sshd.loginGraceTime }}
    LoginGraceTime {{ .Values.sshd.loginGraceTime }}
    {{- else }}
    #LoginGraceTime 2m
    {{- end }}
    {{- if .Values.sshd.permitRootLogin }}
    PermitRootLogin {{ .Values.sshd.permitRootLogin }}
    {{- else }}
    PermitRootLogin prohibit-password
    {{- end }}
    {{- if .Values.sshd.strictModes }}
    StrictModes {{ .Values.sshd.strictModes }}
    {{- else }}
    StrictModes yes
    {{- end }}
    {{- if .Values.sshd.maxAuthTries }}
    MaxAuthTries {{ .Values.sshd.maxAuthTries }}
    {{- else }}
    #MaxAuthTries 6
    {{- end }}
    {{- if .Values.sshd.maxSessions }}
    MaxSessions {{ .Values.sshd.maxSessions }}
    {{- else }}
    #MaxSessions 10
    {{- end }}

    {{- if .Values.sshd.pubKeyAuthentication }}
    PubKeyAuthentication {{ .Values.sshd.pubKeyAuthentication }}
    {{- else }}
    PubkeyAuthentication yes
    {{- end }}

    {{- if .Values.sshd.authorizedKeysFile }}
    AuthorizedKeysFile {{ .Values.sshd.authorizedKeysFile }}
    {{- else }}
    # Expect .ssh/authorized_keys2 to be disregarded by default in future.
    #AuthorizedKeysFile	.ssh/authorized_keys .ssh/authorized_keys2
    {{- end }}

    {{- if .Values.sshd.authorizedPrincipalsFile }}
    AuthorizedPrincipalsFile {{ .Values.sshd.authorizedPrincipalsFile }}
    {{- else }}
    #AuthorizedPrincipalsFile none
    {{- end }}

    {{- if .Values.sshd.authorizedKeysCommand }}
    AuthorizedKeysCommand {{ .Values.sshd.authorizedKeysCommand }}
    {{- else }}
    #AuthorizedKeysCommand none
    {{- end }}
    {{- if .Values.sshd.authorizedKeysCommandUser }}
    AuthorizedKeysCommandUser {{ .Values.sshd.authorizedKeysCommandUser }}
    {{- else }}
    #AuthorizedKeysCommandUser nobody
    {{- end }}

    # For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
    {{- if .Values.sshd.hostBasedAuthentication }}
    HostbasedAuthentication {{ .Values.sshd.hostBasedAuthentication }}
    {{- else }}
    #HostbasedAuthentication no
    {{- end }}
    # Change to yes if you don't trust ~/.ssh/known_hosts for
    # HostbasedAuthentication
    {{- if .Values.sshd.ignoreUserKnownHosts }}
    IgnoreUserKnownHosts {{ .Values.sshd.ignoreUserKnownHosts }}
    {{- else }}
    #IgnoreUserKnownHosts no
    {{- end }}

    # Don't read the user's ~/.rhosts and ~/.shosts files
    #IgnoreRhosts yes

    # To disable tunneled clear text passwords, change to no here!
    {{- if .Values.sshd.passwordAuthentication.enabled }}
    #PasswordAuthentication yes
    {{- else }}
    PasswordAuthentication no
    {{- end }}
    #PermitEmptyPasswords no

    # Change to yes to enable challenge-response passwords (beware issues with
    # some PAM modules and threads)
    ChallengeResponseAuthentication no

    # Kerberos options
    #KerberosAuthentication no
    #KerberosOrLocalPasswd yes
    #KerberosTicketCleanup yes
    #KerberosGetAFSToken no

    # GSSAPI options
    #GSSAPIAuthentication no
    #GSSAPICleanupCredentials yes
    #GSSAPIStrictAcceptorCheck yes
    #GSSAPIKeyExchange no

    # Set this to 'yes' to enable PAM authentication, account processing,
    # and session processing. If this is enabled, PAM authentication will
    # be allowed through the ChallengeResponseAuthentication and
    # PasswordAuthentication.  Depending on your PAM configuration,
    # PAM authentication via ChallengeResponseAuthentication may bypass
    # the setting of "PermitRootLogin without-password".
    # If you just want the PAM account and session checks to run without
    # PAM authentication, then enable this but set PasswordAuthentication
    # and ChallengeResponseAuthentication to 'no'.
    UsePAM yes

    #AllowAgentForwarding yes
    #AllowTcpForwarding yes
    #GatewayPorts no
    X11Forwarding yes
    #X11DisplayOffset 10
    #X11UseLocalhost yes
    #PermitTTY yes
    PrintMotd no
    #PrintLastLog yes
    #TCPKeepAlive yes
    #UseLogin no
    #PermitUserEnvironment no
    #Compression delayed
    #ClientAliveInterval 0
    #ClientAliveCountMax 3
    #UseDNS no
    #PidFile /var/run/sshd.pid
    #MaxStartups 10:30:100
    #PermitTunnel no
    #ChrootDirectory none
    #VersionAddendum none

    # no default banner path
    #Banner none

    # Allow client to pass locale environment variables
    AcceptEnv LANG LC_*

    # override default of no subsystems
    Subsystem	sftp	/usr/lib/openssh/sftp-server

    # Example of overriding settings on a per-user basis
    #Match User anoncvs
    #	X11Forwarding no
    #	AllowTcpForwarding no
    #	PermitTTY no
    #	ForceCommand cvs server
  authorized_keys: |-
    {{- if .Values.authorized_keys }}
    {{ range .Values.authorized_keys }}
    {{ . }}
    {{- end }}
    {{- end }}
