apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openssh-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "openssh-server.name" . }}
    helm.sh/chart: {{ include "openssh-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  sshd_config: |-
    #    $OpenBSD: sshd_config,v 1.101 2017/03/14 07:19:07 djm Exp $

    # This is the sshd server system-wide configuration file.  See
    # sshd_config(5) for more information.

    # This sshd was compiled with PATH=/usr/bin:/bin:/usr/sbin:/sbin

    # The strategy used for options in the default sshd_config shipped with
    # this chart is to specify options with their default value where
    # possible.
    {{ if .Values.sshd.port }}
    Port {{ .Values.sshd.port }}
    {{- else }}
    Port 22
    {{- end }}
    {{- if .Values.sshd.addressFamily }}
    AddressFamily {{ .Values.sshd.addressFamily }}
    {{- else }}
    AddressFamily any
    {{- end }}
    {{- if .Values.sshd.ipv4.enabled }}
    {{- if .Values.sshd.ipv4.listenAddress }}
    ListenAddress {{ .Values.sshd.ipv4.listenAddress }}
    {{- else }}
    ListenAddress 0.0.0.0
    {{- end }}
    {{- end }}
    {{- if .Values.sshd.ipv6.enabled }}
    {{- if .Values.sshd.ipv6.listenAddress }}
    ListenAddress {{ .Values.sshd.ipv6.listenAddress }}
    {{- else }}
    ListenAddress ::
    {{- end }}
    {{- end }}
    {{ if .Values.sshd.hostKeys }}
    {{- range .Values.sshd.hostKeys }}
    Hostkey {{ . }}
    {{- end }}
    {{- else }}
    HostKey /etc/ssh/ssh_host_rsa_key
    HostKey /etc/ssh/ssh_host_ecdsa_key
    HostKey /etc/ssh/ssh_host_ed25519_key
    {{- end }}

    # Ciphers and keying
    {{- if .Values.sshd.reKeyLimit }}
    ReKeyLimit {{ .Values.sshd.reKeyLimit }}
    {{ else }}
    RekeyLimit default none
    {{- end }}

    # Logging
    {{- if .Values.sshd.sysLogFacility }}
    SysLogFacility {{ .Values.sshd.sysLogFacility }}
    {{- else }}
    SyslogFacility AUTH
    {{- end }}
    {{- if .Values.sshd.logLevel }}
    LogLevel {{ .Values.sshd.logLevel }}
    {{- else }}
    LogLevel INFO
    {{- end }}

    # Authentication:
    {{ if .Values.sshd.loginGraceTime }}
    LoginGraceTime {{ .Values.sshd.loginGraceTime }}
    {{- else }}
    LoginGraceTime 2m
    {{- end }}
    {{- if .Values.sshd.permitRootLogin }}
    PermitRootLogin {{ .Values.sshd.permitRootLogin }}
    {{- else }}
    PermitRootLogin prohibit-password
    {{- end }}
    {{- if .Values.sshd.strictModes }}
    StrictModes {{ .Values.sshd.strictModes }}
    {{- else }}
    StrictModes yes
    {{- end }}
    {{- if .Values.sshd.maxAuthTries }}
    MaxAuthTries {{ .Values.sshd.maxAuthTries }}
    {{- else }}
    MaxAuthTries 6
    {{- end }}
    {{- if .Values.sshd.maxSessions }}
    MaxSessions {{ .Values.sshd.maxSessions }}
    {{- else }}
    MaxSessions 10
    {{- end }}
    {{ if .Values.sshd.pubKeyAuthentication }}
    PubKeyAuthentication {{ .Values.sshd.pubKeyAuthentication }}
    {{- else }}
    PubkeyAuthentication yes
    {{- end }}
    {{ if .Values.sshd.authorizedKeysFile }}
    AuthorizedKeysFile {{ .Values.sshd.authorizedKeysFile }}
    {{- else }}
    # Expect .ssh/authorized_keys2 to be disregarded by default in future.
    AuthorizedKeysFile    .ssh/authorized_keys .ssh/authorized_keys2
    {{- end }}
    {{ if .Values.sshd.authorizedPrincipalsFile }}
    AuthorizedPrincipalsFile {{ .Values.sshd.authorizedPrincipalsFile }}
    {{- else }}
    AuthorizedPrincipalsFile none
    {{- end }}
    {{ if .Values.sshd.authorizedKeysCommand }}
    AuthorizedKeysCommand {{ .Values.sshd.authorizedKeysCommand }}
    {{- else }}
    AuthorizedKeysCommand none
    {{- end }}
    {{- if .Values.sshd.authorizedKeysCommandUser }}
    AuthorizedKeysCommandUser {{ .Values.sshd.authorizedKeysCommandUser }}
    {{- else }}
    AuthorizedKeysCommandUser nobody
    {{- end }}
    {{ if .Values.sshd.kexAlgorithms }}
    KexAlgorithms {{ .Values.sshd.kexAlgorithms }}
    {{- else }}
    KexAlgorithms diffie-hellman-group-exchange-sha256
    {{- end }}
    {{- if .Values.sshd.ciphers }}
    Ciphers {{ .Values.sshd.ciphers }}
    {{- else }}
    Ciphers aes256-cbc,aes256-ctr
    {{- end }}
    {{- if .Values.sshd.messageAuthenticationCodes }}
    MACs {{ .Values.sshd.messageAuthenticationCodes }}
    {{- else }}
    MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-256
    {{- end }}

    # For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
    {{- if .Values.sshd.hostBasedAuthentication }}
    HostbasedAuthentication {{ .Values.sshd.hostBasedAuthentication }}
    {{- else }}
    HostbasedAuthentication no
    {{- end }}
    # Change to yes if you don't trust ~/.ssh/known_hosts for
    # HostbasedAuthentication
    {{- if .Values.sshd.ignoreUserKnownHosts }}
    IgnoreUserKnownHosts {{ .Values.sshd.ignoreUserKnownHosts }}
    {{- else }}
    IgnoreUserKnownHosts no
    {{- end }}
    # Don't read the user's ~/.rhosts and ~/.shosts files
    {{- if .Values.sshd.ignoreRhosts }}
    IgnoreRhosts yes
    {{- else }}
    IgnoreRhosts no
    {{- end }}

    # To disable tunneled clear text passwords, change to no here!
    {{- if .Values.sshd.passwordAuthentication }}
    PasswordAuthentication yes
    {{- else }}
    PasswordAuthentication no
    {{- end }}
    {{- if .Values.sshd.permitEmptyPasswords }}
    PermitEmptyPasswords yes
    {{- else }}
    PermitEmptyPasswords no
    {{- end }}

    # Change to yes to enable challenge-response passwords (beware issues with
    # some PAM modules and threads)
    {{- if .Values.sshd.challengeResponseAuthentication }}
    ChallengeResponseAuthentication yes
    {{- else }}
    ChallengeResponseAuthentication no
    {{- end }}

    # Kerberos options
    {{- if .Values.sshd.kerberosAuthentication.enabled }}
    KerberosAuthentication yes
    {{- if .Values.sshd.kerberosAuthentication.orLocalPassword }}
    KerberosOrLocalPasswd yes
    {{- else }}
    KerberosOrLocalPasswd no
    {{- end }}
    {{- if .Values.sshd.kerberosAuthentication.ticketCleanup }}
    KerberosTicketCleanup yes
    {{- else }}
    KerberosTicketCleanup no
    {{- end }}
    {{- if .Values.sshd.kerberosAuthentication.getAFSToken }}
    KerberosGetAFSToken yes
    {{- else }}
    KerberosGetAFSToken no
    {{- end }}
    {{- else }}
    KerberosAuthentication no
    {{- end }}

    # GSSAPI options
    {{- if .Values.sshd.gssApiAuthentication.enabled }}
    GSSAPIAuthentication yes
    {{- if .Values.sshd.gssApiAuthentication.cleanupCredentials }}
    GSSAPICleanupCredentials yes
    {{- else }}
    GSSAPICleanupCredentials no
    {{- end }}
    {{- if .Values.sshd.gssApiAuthentication.strictAcceptorCheck }}
    GSSAPIStrictAcceptorCheck yes
    {{- else }}
    GSSAPIStrictAcceptorCheck no
    {{- end }}
    {{- if .Values.sshd.gssApiAuthentication.keyExchange }}
    GSSAPIKeyExchange yes
    {{- else }}
    GSSAPIKeyExchange no
    {{- end }}
    {{- else }}
    GSSAPIAuthentication no
    {{- end }}

    # Set this to 'yes' to enable PAM authentication, account processing,
    # and session processing. If this is enabled, PAM authentication will
    # be allowed through the ChallengeResponseAuthentication and
    # PasswordAuthentication.  Depending on your PAM configuration,
    # PAM authentication via ChallengeResponseAuthentication may bypass
    # the setting of "PermitRootLogin without-password".
    # If you just want the PAM account and session checks to run without
    # PAM authentication, then enable this but set PasswordAuthentication
    # and ChallengeResponseAuthentication to 'no'.
    {{- if .Values.sshd.usePam }}
    UsePAM yes
    {{- else }}
    UsePAM no
    {{- end }}

    {{ if .Values.sshd.allowAgentForwarding }}
    AllowAgentForwarding yes
    {{- else }}
    AllowAgentForwarding no
    {{- end }}
    {{- if .Values.sshd.allowTcpForwarding }}
    AllowTcpForwarding yes
    {{- else }}
    AllowTcpForwarding no
    {{- end }}
    {{- if .Values.sshd.gatewayPorts }}
    GatewayPorts yes
    {{- else }}
    GatewayPorts no
    {{- end }}
    {{- if .Values.sshd.x11Forwarding }}
    X11Forwarding yes
    {{- else }}
    X11Forwarding no
    {{- end }}
    {{- if .Values.sshd.x11DisplayOffset }}
    X11DisplayOffset {{ .Values.sshd.x11DisplayOffset.offset }}
    {{- else }}
    X11DisplayOffset 10
    {{- end }}
    {{- if .Values.sshd.x11UseLocalHost }}
    X11UseLocalhost yes
    {{- else }}
    X11UseLocalhost no
    {{- end }}
    {{- if .Values.sshd.permitTTY }}
    PermitTTY yes
    {{- else }}
    PermitTTY no
    {{- end }}
    {{- if .Values.sshd.printMotd }}
    PrintMotd yes
    {{- else }}
    PrintMotd no
    {{- end }}
    {{- if .Values.sshd.printLastLog }}
    PrintLastLog yes
    {{- else }}
    PrintLastLog no
    {{- end }}
    {{- if .Values.sshd.tcpKeepAlive }}
    TCPKeepAlive yes
    {{- else }}
    TCPKeepAlive no
    {{- end }}
    {{- if .Values.sshd.useLogin }}
    UseLogin yes
    {{- else }}
    UseLogin no
    {{- end }}
    {{- if .Values.sshd.permitUserEnvironment }}
    PermitUserEnvironment yes
    {{- else }}
    PermitUserEnvironment no
    {{- end }}

    {{- if .Values.sshd.compression }}
    Compression {{ .Values.sshd.compression }}
    {{- else }}
    Compression delayed
    {{- end }}

    {{- if .Values.sshd.clientAliveInterval }}
    ClientAliveInterval {{ .Values.sshd.clientAliveInterval }}
    {{- else }}
    ClientAliveInterval 0
    {{- end }}
    {{- if .Values.sshd.clientAliveCountMax }}
    ClientAliveCountMax {{ .Values.sshd.clientAliveCountMax }}
    {{- else }}
    ClientAliveCountMax 3
    {{- end }}
    {{- if .Values.sshd.useDNS }}
    UseDNS yes
    {{- else }}
    UseDNS no
    {{- end }}
    {{- if .Values.sshd.pidFile }}
    PidFile {{ .Values.sshd.pidFile }}
    {{- else }}
    PidFile /var/run/sshd.pid
    {{- end }}
    {{- if .Values.sshd.maxStartups }}
    MaxStartups {{ .Values.sshd.maxStartups }}
    {{- else }}
    MaxStartups 10:30:100
    {{- end }}
    {{- if .Values.sshd.permitTunnel }}
    PermitTunnel yes
    {{- else }}
    PermitTunnel no
    {{- end }}
    {{- if .Values.sshd.chrootDirectory }}
    ChrootDirectory {{ .Values.sshd.chrootDirectory }}
    {{- else }}
    ChrootDirectory none
    {{- end }}
    {{- if .Values.sshd.versionAddendum }}
    VersionAddendum {{ .Values.sshd.versionAddendum }}
    {{- else }}
    VersionAddendum none
    {{- end }}

    # no default banner path
    {{- if .Values.sshd.banner }}
    Banner {{ .Values.sshd.banner }}
    {{- else }}
    Banner none
    {{- end }}

    # Allow client to pass locale environment variables
    {{- if .Values.sshd.acceptEnv.enabled }}
    {{- range .Values.sshd.acceptEnv.variables }}
    AcceptEnv {{ . }}
    {{- end }}
    {{- else }}
    AcceptEnv none
    {{- end }}

    # override default of no subsystems
    {{- if .Values.sshd.subsystems.enabled }}
    {{- range .Values.sshd.subsystems.systems }}
    Subsystem {{ .name }}    {{ .value }}
    {{- end }}
    {{- else }}
    Subsystem none
    {{- end }}

    # Example of overriding settings on a per-user basis
    {{- if .Values.sshd.matchUser.enabled }}
    {{- range .Values.sshd.matchUser.users }}
    Match User {{ .name }}
    {{- range .settings }}
        {{ .name }} {{ .value }}
    {{- end }}
    {{- end }}
    {{- end }}
  authorized_keys: |-
    {{- if .Values.authorized_keys }}
    {{ range .Values.authorized_keys }}
    {{ . }}
    {{- end }}
    {{- end }}
