version: '3.7'
services:
  openssh:
    image: 'openssh-server'
    container_name: 'openssh'
    hostname: 'openssh'
    domainname: 'lazybit.ch'
    restart: 'always'
    volumes:
    - 'openssh:/etc/ssh'
    - './etc/ssh/sshd_config:/etc/ssh/sshd_config:ro'
    - './etc/ssh/ssh_config:/etc/ssh/ssh_config:ro'
    cap_add:
    - 'SYS_CHROOT'
    - 'SETGID'
    - 'SETUID'
    - 'CHOWN'
    ports:
    - '22:22'
volumes:
  openssh:
