apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
  - image: openssh-server
    docker:
      cacheFrom:
      - 'ubuntu:18.04'
  local:
    push: false
    useBuildkit: true
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}'
